### ISSUE TITLE
Support wider citation syntax

### ISSUE THREAD

**Issue by Neved4** [typst/typst#1139]
I believe I speak for many when I say that `typst` is a breath of fresh air for the typesetting community, and an excellent learning experience for newcomers. Keep rocking 🚀

Related: https://github.com/typst/typst/issues/658 ([@JKRhb](https://github.com/JKRhb))

## Proposal

`typst` is a project draws inspiration from previous projects while improving upon them with new takes on previous ideas. I'd want that `typst` would give more control for citations to users. There are some projects that already do this, like Biblatex's `\citeauthor`, `\citeyear`, `\citetitle`[^1], while other projects are taking several years to incorporate similar changes, such as Pandoc[^2]. In that Pandoc discussion, the CommonMark forums[^3] and other recent projects [^4] there are plenty ideas for compact, easy to read syntax. This proposal takes those into account, and the principles in the README:

> If you know how to do one thing in Typst, you should be able to transfer that knowledge to other things. If there are multiple ways to do the same thing, one of them should be at a different level of abstraction than the other.

> There are two ways to make something flexible: Have a knob for everything or have a few knobs that you can combine in many ways. Typst is designed with the second way in mind. We provide systems that you can compose in ways we've never even thought of.

Here I present some ideas regarding syntax, you'll like some and dislike others. Ultimately, what matters most is that the features are implemented rather than the specific syntax sugar. Overall, some of the following additions may or may not make sense for the project. Feel free to choose the ones that best align to `typyst`'s scope and aesthetics.

### P1. Extend cite parameters

While the current `#cite` expression works great[^5], it could benefit from additional control in some situations. I propose the inclusion of the following parameters:

- `field` parameter, that allows users to select specific fields to be typeset in the citation.
- `page` parameter, similar to the [p.~N] supplement of the reference syntax, allowing users to specify a specific page number to be cited.
- `pages` parameter, that enables users to cite specific page ranges.

Cite parameters:
```css
#cite(
  ..string,
  nonecontent,
  brackets: boolean,
  style: auto string,
  field: string, /* (e.g.: "title") */
  page: int /* (e.g.: "7") */
  pages: int range /* (e.g.: "9-18") */
) -> content
```
 
### P2. Extend reference syntax

Reference syntax:
```css
@name(p.~7)
@name(pp.~7-18)
@name(author) /* alias: +@name, @name(+) */
@name(title) /* alias: =@name, @name(=) */
@name(year) /* alias: -@name, @name(-) */
@name(full), /* alias: *@name, @name(*) */
```

This proposal tries to be harmonious with the existing language, and I understand how brackets could be preferred, to match the already existing page notation. At the same time, there's appeal in how `typst` uses parentheses across the language and they're more fitting with the rest of the syntax, separating `typst` clearly from LaTeX and Markdown variants:

<img width="822" alt="Screenshot 2023-05-07 at 14 43 53" src="https://user-images.githubusercontent.com/63655535/236678980-6f094a1d-a828-4622-99c3-3318f840f16f.png">

Having aliases could also be a nice perk and make things look more compact in some situations. However, aliases are not fundamental and I acknowledge that having them could potentially complicate the compiler and syntax highlighting logic.

## Examples

All BibTeX data is from `works.bib`[^6]

### P1. Examples

Using the expression syntax:
```css
#cite(
    ("netwok", page: "7"),
    ("netwok", field: "author"),
    ("tolkien54", field: "title")
)
```

**Expected output**  
> \[1\](p. 7), Linda Morris, _The Lord of the Rings_

A more compact alternative:
```css
#cite("netwok", "tolkien54(author)")
```

### P2. Examples

Using the reference syntax:
```css
@netwok(p.~7), @netwok(author), @tolkien54(title)
```

**Expected output**
> \[1\](p. 7), Linda Morris, _The Lord of the Rings_

With square brackets:
```css
@netwok[p.~7], @netwok[author], @tolkien54[title]
```

Citing title and author example:
```text
In the book @tolkien54(title), author @tolkien54(author) masterfully depicts...
```

**Expected output**
> In the book _The Fellowship of the Ring_, author J. R. R. Tolkien masterfully depicts ...

Citing fulltitle:
```text
This was already illustrated in @tolkien54[*].
```

**Expected output**
> This was already illustrated in: J. R. R. Tolkien. _The Lord of the Rings_. Vol. 1: _The Fellowship of the Ring_. London: Allen & Unwin, July 29, 1954.

### Tasks

- [ ] ref cite author - `@name[author]`
- [ ] ref cite title - `@name[title]`
- [ ] ref cite year - `@name[year]`
- [ ] ref full cite - `@name[full]`, `@name[*]`
- [x] ref cite page - `@name[p.~7]`
- [ ] ref cite pages - `@name[pp.~7-12]`
- [ ] exp cite field - `#cite("name", field: "author")`
- [ ] exp cite page - `#cite("name", page: 7)`
- [ ] exp cite pages - `#cite("name", pages: 7-12)`

##### N.B.: This proposal could be extended to consider future, interesting usecases that ressemble the `\footcite`, `\textcite`, `\parencite`, `\smartcite` present in the LaTeX world and are advantageous when typesetting bibliographies.

[^1]: https://osl.ugr.es/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf
[^2]: https://github.com/jgm/pandoc/issues/2335
[^3]: https://talk.commonmark.org/
[^4]: https://github.com/bcdavasconcelos/cite-field
[^5]: https://typst.app/docs/reference/meta/cite#parameters
[^6]: https://github.com/typst/typst/blob/main/assets/files/works.bib

## Use Case

- Avoids redundancy in texts that repeat long titles and authors.
- Gives more control over citing specific fields of a bibliography entry.
- Serves as a foundation for the generation of author indexes and appendixes, telling the engine where said author or title was mentioned in.

Take this source:
```text
In "The Chronicles of Narnia: The Lion, the Witch and the
Wardrobe", a fantasy novel written by C.S. Lewis introduces
readers to the magical world...

Because of that, C.S. Lewis decided to write "The Chronicles of
Narnia: The Lion, the Witch and the Wardrobe" in 1950 after the
events...
```

And compare it with this one:
```css
In @lewis50[title], a fantasy novel written by @lewis50[author]
introduces readers to the magical world...

Because of that, @lewis50[author] decided to write @lewis50[title]
in @lewis50[year] after the events...
```

With aliases:
```css
In =@lewis50, a fantasy novel written by +@lewis50
introduces readers to the magical world...

Because of that, +@lewis50 decided to write =@lewis50
in -@lewis50 after the events...
```

**Expected output**
> In _"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"_, a fantasy novel written by C.S. Lewis introduces readers to the magical world...
>
> Because of that, C.S. Lewis decided to write _"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"_ in 1950 after the events...

**Comment by mnrvwl** [comment]
@JKRhb Since you're the first one who contributed to this discussion (https://github.com/typst/typst/issues/658) I'd love to have your thoughts and extend the proposal in any way. We could also combine both issues into one if you'd be up for it.

**Comment by cbr9** [comment]
This is the main issue keeping me from completely switching to Typst. What is the status of this? :)

**Comment by laurmaedje** [comment]
> This is the main issue keeping me from completely switching to Typst. What is the status of this? :)

Not much progress unfortunately. We'll definitely get to improving the citation and bibliography management, but it will take a bit of time.

**Comment by turbanisch** [comment]
I'd love to see something like this implemented as well! I just noticed recently that there is no way (using `style: "chicago-author-date"`) to display author and date without any parentheses (which I would like to do when they are used inside of another pair of parentheses, e.g. "(see @citekey)").

Perhaps this could even be implemented to be context-sensitive (i.e., choose the correct form depending on whether wrapped in parentheses) as done by Quarto/RMarkdown? https://quarto.org/docs/authoring/footnotes-and-citations.html

**Comment by briochemc** [comment]
👋 Just a reminder to add the prenote and postnote features to the list of tasks! 😃

**Comment by briochemc** [comment]
> I'd love to see something like this implemented as well! I just noticed recently that there is no way (using `style: "chicago-author-date"`) to display author and date without any parentheses (which I would like to do when they are used inside of another pair of parentheses, e.g. "(see @citekey)").

FWIW, I have been using this as a workaround:
```typst
#let citeauthoryear(label) = {
  [#cite(label, form:"author"), #cite(label, form:"year")]
}
```

and then use `(see citeauthoryear(<citekey>))`.

**Comment by laurmaedje** [comment]
Since this issue was opened, we've shipped the CSL feature and [citation forms](https://typst.app/docs/reference/model/cite/#parameters-form). I understand this system might still not serve all use cases explained here. However, the issue is not really actionable as-is, so it would be better to open individual issues for specific features that are still missing (if those issues don't already exist).

**Comment by Neved4** [comment]
Sounds good! ✌🏻

**Comment by marcelroed** [comment]
@briochemc Do you have a way to do this for "FAuthor et. al (YYYY)"?

**Comment by padok** [comment]
Hey!

So since Typst got CSL support, we can create tiny, per‑citation styles that render inline citations as:

Author’s Title (Year)
Author’s (Year)
Author’s
Author (Year)
Author
Title (italic)

…and each one remains a single clickable link to the bibliography entry.

This enables us to write, for example:

“Knuth’s (1984) concept…”
“As discussed by Knuth (1984)…”
“In Literate Programming, he argued…”

So here is the proof of concept I came up with:

```typst
Some examples:
- @knuth:1984
- #cite_atyp(<knuth:1984>)  // Knuth’s _Literate Programming_ (1984)
- #cite_ayp(<knuth:1984>)  // Knuth’s (1984)
- #cite_ap(<knuth:1984>)   // Knuth’s
- #cite_ay(<knuth:1984>)   // Knuth (1984)
- #cite_a(<knuth:1984>)    // Knuth
- #cite_t(<knuth:1984>)    // _Literate Programming_

#bibliography(bytes(data), style: "apa")
```


<img width="515" height="286" alt="Image" src="https://github.com/user-attachments/assets/41c0d878-2331-45f2-b42b-b789c00fa087" />

> [!NOTE]
> Edit: Added supplement support

> [!IMPORTANT]
>
> <details>
>   <summary>Click here for the complete example</summary>
>
> ```typst
> #let title_only_italic_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info>
>     <title>Title only (italic, optional supplement)</title>
>     <id>urn:typst:title-only-italic</id>
>   </info>
>
>   <macro name="the-title">
>     <text variable="title" font-style="italic"/>
>   </macro>
>
>   
>   <macro name="supp">
>     <choose>
>       <if variable="issued locator" match="any">
>         <group prefix="(" suffix=")">
>           <group delimiter=", ">
>             <text variable="locator"/>
>           </group>
>         </group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="the-title"/>
>         <text macro="supp"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <group delimiter=" ">
>         <text macro="the-title"/>
>         <text macro="supp"/>
>       </group>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_t(key, ..args) = cite(key, style: bytes(title_only_italic_csl), ..args) // *The Book Title*
>
> #let author_only_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info><title>Author only</title><id>urn:typst:author-only</id></info>
>
>   <macro name="the-author">
>     <choose>
>       <if variable="author">
>         <names variable="author" and="text" delimiter=", ">
>           <name form="short"/>
>         </names>
>       </if>
>     </choose>
>   </macro>
>
>   
>   <macro name="supp-parens">
>     <choose>
>       <if variable="locator">
>         <group prefix="(" suffix=")"><text variable="locator"/></group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="the-author"/>
>         <text macro="supp-parens"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <group delimiter=" ">
>         <text macro="the-author"/>
>         <text macro="supp-parens"/>
>       </group>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_a(key, ..args) = cite(key, style: bytes(author_only_csl), ..args) // Smith
>
> #let author_year_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info><title>Author (Year[, supplement])</title><id>urn:typst:author-year</id></info>
>
>   <macro name="the-author">
>     <choose>
>       <if variable="author">
>         <names variable="author" and="text" delimiter=", ">
>           <name form="short"/>
>         </names>
>       </if>
>     </choose>
>   </macro>
>
>   <macro name="year-and-supp">
>     <choose>
>       <if variable="issued locator" match="any">
>         <group prefix="(" suffix=")">
>           <group delimiter=", ">
>             <date variable="issued"><date-part name="year"/></date>
>             <text variable="locator"/>
>           </group>
>         </group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="the-author"/>
>         <text macro="year-and-supp"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <text macro="the-author"/>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_ay(key, ..args) = cite(key, style: bytes(author_year_csl), ..args) // Smith (2000)
>
> #let author_pos_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info><title>Author’s</title><id>urn:typst:author-pos</id></info>
>
>   <macro name="author-pos">
>     <choose>
>       <if variable="author">
>         <names variable="author" and="text" delimiter=", " suffix="’s">
>           <name form="short"/>
>         </names>
>       </if>
>     </choose>
>   </macro>
>
>   <macro name="supp-parens">
>     <choose>
>       <if variable="locator">
>         <group prefix="(" suffix=")"><text variable="locator"/></group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="author-pos"/>
>         <text macro="supp-parens"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <group delimiter=" ">
>         <text macro="author-pos"/>
>         <text macro="supp-parens"/>
>       </group>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_ap(key, ..args) = cite(key, style: bytes(author_pos_csl), ..args) // Smith’s
>
> #let author_pos_year_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info><title>Author’s (Year[, supplement])</title><id>urn:typst:author-pos-year</id></info>
>
>   <macro name="author-pos">
>     <choose>
>       <if variable="author">
>         <names variable="author" and="text" delimiter=", " suffix="’s">
>           <name form="short"/>
>         </names>
>       </if>
>     </choose>
>   </macro>
>
>   <macro name="year-and-supp">
>     <choose>
>       <if variable="issued locator" match="any">
>         <group prefix="(" suffix=")">
>           <group delimiter=", ">
>             <date variable="issued"><date-part name="year"/></date>
>             <text variable="locator"/>
>           </group>
>         </group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="author-pos"/>
>         <text macro="year-and-supp"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <text macro="author-pos"/>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_ayp(key, ..args) = cite(key, style: bytes(author_pos_year_csl), ..args) // Smith’s (2000)
>
> #let author_title_year_csl = ```xml
> <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text">
>   <info>
>     <title>Author’s *Title* (Year[, supplement])</title>
>     <id>urn:typst:author-title-year-italic</id>
>   </info>
>
>   <macro name="author-pos">
>     <choose>
>       <if variable="author">
>         <names variable="author" and="text" delimiter=", " suffix="’s">
>           <name form="short"/>
>         </names>
>       </if>
>     </choose>
>   </macro>
>
>   <macro name="the-title">
>     <text variable="title" font-style="italic"/>
>   </macro>
>
>   <macro name="year-and-supp">
>     <choose>
>       <if variable="issued locator" match="any">
>         <group prefix="(" suffix=")">
>           <group delimiter=", ">
>             <date variable="issued"><date-part name="year"/></date>
>             <text variable="locator"/>
>           </group>
>         </group>
>       </if>
>     </choose>
>   </macro>
>
>   <citation>
>     <layout>
>       <group delimiter=" ">
>         <text macro="author-pos"/>
>         <text macro="the-title"/>
>         <text macro="year-and-supp"/>
>       </group>
>     </layout>
>   </citation>
>
>   <bibliography>
>     <layout>
>       <group delimiter=" ">
>         <text macro="author-pos"/>
>         <text macro="the-title"/>
>         <text macro="year-and-supp"/>
>       </group>
>     </layout>
>   </bibliography>
> </style>
> ```.text
>
> #let cite_atyp(key, ..args) = cite(key, style: bytes(author_title_year_csl), ..args) // Smith’s _the great title_ (2000)
>
>
> #let data = ```
> @article{knuth:1984,
>   title={Literate Programming},
>   author={Donald E. Knuth},
>   journal={The Computer Journal},
>   volume={27},
>   number={2},
>   pages={97--111},
>   year={1984},
>   publisher={Oxford University Press}
> }
> ```.text
>
> Some examples:
> - @knuth:1984
> - #cite_atyp(<knuth:1984>) // Knuth’s _Literate Programming_ (1984)
> - #cite_ayp(<knuth:1984>)  // Knuth’s (1984)
> - #cite_ap(<knuth:1984>)   // Knuth’s
> - #cite_ay(<knuth:1984>)   // Knuth (1984)
> - #cite_a(<knuth:1984>)    // Knuth
> - #cite_t(<knuth:1984>)    // _Literate Programming_
>
> Some examples with supplement:
> - #cite(<knuth:1984>, supplement: [p. 12])      // (Knuth, 1984, p. 12)
> - #cite_atyp(<knuth:1984>, supplement: [p. 12]) // Knuth’s _Literate Programming_ (1984, p. 12)
> - #cite_ayp(<knuth:1984>, supplement: [p. 12])  // Knuth’s (1984, p. 12)
> - #cite_ap(<knuth:1984>, supplement: [p. 12])   // Knuth’s (p. 12)
> - #cite_ay(<knuth:1984>, supplement: [p. 12])   // Knuth (1984, p. 12)
> - #cite_a(<knuth:1984>, supplement: [p. 12])    // Knuth (p. 12)
> - #cite_t(<knuth:1984>, supplement: [p. 12])    // _Literate Programming_ (p. 12)
>
> #bibliography(bytes(data), style: "apa")
> ```
> </details>
