### ISSUE TITLE
Gradient - Tracking issue

### ISSUE THREAD

**Issue by Dherse** [typst/typst#2282]
# Gradient progress report:
- [x] Part 1: Color rework #2171 
- [x] Part 1a: Color fixes #2262 
- [x] Part 2: Linear gradients #2279
- [ ] Part 3: Radial gradients
- [ ] Part 4: Conic gradients
- [ ] Part 5: Gradients on text
- [ ] Part 6: Additional gradient features

The vast majority of those features (all of them in SVG) are available on my [gradient](https://github.com/Dherse/typst/tree/gradient) branch. However, in this branch the layout engine is completely broken, which I have fixed in this PR, but didn't bother to on my experimental branch.

This is just a tracking issue I can point to in other gradient PRs ;)

**Comment by Dherse** [comment]
Also closes #443 (with Part 8).

**Comment by Dherse** [comment]
Also closes #260. I'd even go as far as stating that it already closes it.

**Comment by Dherse** [comment]
It was decided in discussion with @laurmaedje that we would not support (at least now) glyph-by-glyph gradients as they're extremely heavy file-size wise, kind of ugly, and difficult to get right.

**Comment by stellarpower** [comment]
This looks fab! Would building it be as simple as pointing rust to a crate from your fork? Afraid I've not much experience with the language. I would like some gradients in my document, so I can do some basic testing.

**Comment by laurmaedje** [comment]
@stellarpower Most of the gradient work has already landed on main, so if you just compile Typst from main you can just use it.

**Comment by stellarpower** [comment]
As of a5966636, it seems that I can fill a box with a gradient (`fill` can take a `gradient`) - but the `stroke` for `line`s doesn't seem to support this; is this worth adding as a subitem above? I imagine single straight lines ought to be a simpler starting point than arbitrary paths or font glyphs, and would enable people to take it for a spin in more situations!

**Comment by Dherse** [comment]
@stellarpower With regards to line, they generally you work, you can find an example [here](https://github.com/typst/typst/blob/main/tests/typ/visualize/gradient-stroke.typ) but I generally recommend keeping simple linear gradients on line as line technically have a zero width which makes other gradient look... funky?

>  I imagine single straight lines ought to be a simpler starting point than arbitrary paths or font glyphs

Truth be told, there is essentially no difference wrt. the "complexity" of the stroke for gradient fills. Currently, gradient fills in parent mode will work on any path you throw at them, it's only when applied in `relative: "self"` or `relative: "auto"` on lines that it can get tricky.

**Comment by stellarpower** [comment]
Okay, so I have to do the `1pt + ` bit, I presume that turns it from a gradient to a stroke.

It seems that fill accepts a gradient or a color, whilst line accepts a color or a stroke (which can be based off a gradient itself), but not a gradient.

Thanks for the advice on your branch, I'll stay clear then.

**Comment by emilyyyylime** [comment]
> Okay, so I have to do the `1pt + ` bit, I presume that turns it from a gradient to a stroke.
Also consider `stroke: (paint: gradient(..))`

**Comment by laurmaedje** [comment]
Should we close this?

**Comment by Dherse** [comment]
I was planning on working on some more features, namely pattern fills in the upcoming weeks just haven't found the motivation just yet

**Comment by gregzanch** [comment]
Should #5647 be included for number 9 on the list?

**Comment by ibnz36** [comment]
Hello. what's the state of Part 7? It seems to work on the preview but doesn't when exporting to a PDF.

Code:
```typ
#let g1 = green.transparentize(90%)
#rect(fill: gradient.linear(blue, g1))
```

Exported:

[bugtest.pdf](https://github.com/user-attachments/files/20395577/bugtest.pdf)

**Comment by Dherse** [comment]
@ibnz36 I just updated the tracking issue with the change done in #5420 which added support for transparency gradient in PDF :)

**Comment by ibnz36** [comment]
@Dherse Should #2546 be reopened?

**Comment by LaurenzV** [comment]
As mentioned in the issue, the fix doesn't exist in the latest Typst release yet, you need to use the current devevelopment branch if you want the fix.

**Comment by ibnz36** [comment]
Oh, I see. Ty
