### ISSUE TITLE
Tracking Issue: Interactive Forms

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#2421]
# Description
This is a tracking issue for implementing interactive forms.

In order to support interactive forms with partial compliance to [PDF 1.7], pdf-writer must first support most of section 12.7 as well as a few other parts of the 1.7 spec which this section depends on. Certain features which are known to be deprecated in specs after 1.7, such as XFA forms, will not be implemented.

# Tasks
The following work has to be done, this list will be updated as new issues arise or feature sets are requested/dropped. Some of these features could later be dropped as optional or unneeded.

## Bugs
- [ ] typst/pdf-writer#15

## Features
- [ ] Appearance streams (**12.5.5**)
- [x] Support actions (**12.6**)
- [ ] Interactive Forms (**12.7**)
  - [ ] Interactive Form Dictionary (**12.7.2**)
    - [x] *requires* Resource Dictionary (**7.8.3**)
    - [ ] *requires* typst/pdf-writer#21
    - [x] *requires* typst/pdf-writer#20
  - [ ] Field Dictionaries (**12.7.3**)
  - [ ] Field Types (**12.7.4**)
    - [ ] Text fields (**12.7.4.2**)
    - [ ] Choice fields (**12.7.4.3**)
    - [ ] Button fields (**12.7.4.4**)
    - [ ] Signature fields (**12.7.4.5**)
  - [ ] Named Pages (**12.7.6**)
    - [ ] *requires* Named Dictionaries (**7.7.4**)
       - [ ] *requires* Name Trees (**7.9.6**)

# Motivation
The primary motivator is resolving https://github.com/typst/typst/issues/1765.

[PDF 1.7]: https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

# Discussion
Please keep this issue clean of discussion, use any of the linked discussions or issues if need be. I will regularly update this PR and send a comment when that status changes or a feature set was completed.

**Comment by tingerrr** [comment]
I am now in the testing phase of my contributions to pdf-writer, including my latest draft PR, to ensure that it all works and exposes a functional API. It'll take a while to get a working form document, because it's so deeply intertwined with other PDF features I have yet to grasp.

**Comment by tingerrr** [comment]
To those interested in the progress of this feature, if you have documents you could share with me, which contain the following form features, I would greatly appreciate it.

- [ ] text fields, if possible, with auto scrolling and resizing
- [ ] choice fields, a field where you pick one or multiple items from a dropdown list
- [ ] Radio buttons
  - preferably multiple ones that are switched in unison, e.g.: `[x] yes, [ ] no` and only one can be activated
  - but also those where multiple radio buttons refer to the same form entry, i.e. switching a row on one page also switches the row on another page
- [ ] signature fields, although they are not yet implemented, so I won't test those, but they'll be helpful in the future

Bonus points if they have different appearances when active, hovered, clicked, etc.

I will handle these documents with discretion if they contain sensitive data, but I understand if you don't want to send a stranger on the internet such a document.

**Comment by StefanSchroeder** [comment]
I'd love to alpha-test this new feature. Any timeline? No pressure, just asking.

**Comment by tingerrr** [comment]
Once typst/pdf-writer#25 is merged, work on experimental form elements can begin.

**Comment by tingerrr** [comment]
I have opened #4174 to get support for export target specific code, I believe this is integral to make the lower-level features such as export target specific code (i.e. forms) easier to handle in user code.

**Comment by tingerrr** [comment]
I've already posted this in the forge on Discord, but I know Discord ain't for everyone, so I'm posting a TLDR here:

I don't think I'll have the time to finish this anytime soon. The gist is that I don't have a lot of free time right now, and when I do, my time is taken up by other projects. This feature shouldn't be blocked by me when someone else could be working on this in the meantime.

If someone wants to implement this, feel free to reach out to me via email or discord (on the fore in the community discord) and I'll share my experience with reader support and quirks to get you up to speed. You may need to create a new tracking issue to be able to edit it, I don't think one can transfer issues on GitHub or allow non maintainers to edit them.

I apologize for blocking this for so long.

**Comment by geoffreygarrett** [comment]
Hi, I can't seem to find a working link for the typst discord anywhere. I wanted to DM you and ask how much work you think it would take to get it done 🙂
