### ISSUE TITLE
Spellchecking: How?

### ISSUE THREAD

**Issue by antonWetzel** [typst/typst#2427]
## Description

Specify the official/recommended way for spellcheck.

## Questions
- Implementation location?
  - [ ] Compiler
  - [ ] WebApp
- Scope?
  - [ ] Dictionary check
  - [ ] + Grammer check
  - [ ] + Style check
  - [ ] + ...?
- What to check?
  - [ ] Source (AST)
  - [ ] Output (PDF/Content before final export) 
- How to check?
  - [ ] Use external spellchecker
  - [ ] Use Rust package (could not find a big one)
  - [ ] Custom solution

## References for Typst Spellcheck
- https://github.com/typst/typst/pull/2417
- https://github.com/typst/typst/discussions/2423
- https://github.com/typst/webapp-issues/issues/141

## References for Spellcheckers
- https://languagetool.org/
- http://aspell.net/
- http://hunspell.github.io/
- https://github.com/pluots/zspell

## Other
- Interface for local LanguageToolServer
  - https://github.com/antonWetzel/typst-languagetool
- VSCode extension with builtin LanguageTool (without typst support)
  - https://github.com/valentjn/vscode-ltex
  
## Personal opinion
- Build custom solution for typst with
  - spellchecker as external crate (like https://github.com/typst/pdf-writer)
  - interface in typst-cli crate
  - build scope incremental
  - check source, not output
- The best "value" is integrating an external spellchecker, but I don't like non rust dependencies

**Comment by emilyyyylime** [comment]
Spell checking isn't Typst's responsibility and an external spellchecker isn't a dependency. I think spellchecking would be most elegantly implemented as WASM plugins

**Comment by Dherse** [comment]
@emilyyyylime I disagree some some extent: I would expect typst to at least provide facilities for implementing spellchecking (such as at the AST level) externally, typically in an LSP implementation, as well as being doable on the webapp reliably. Providing these facilities should be in-scope for typst, but I agree that it's very unlikely we'll be building our own spellchecker.

**Comment by KillTheMule** [comment]
> * check source, not output

I'd have to disagree here, seeing how many scripting facilities typst has. Can one be really sure what the final output strings are before going through all the motions?

Imho the text render output would deal with this pretty nicely.

**Comment by emilyyyylime** [comment]
@Dherse Sorry, I definitely did not intend that Typst should turn a blind eye towards any form of spellcheck — I entirely agree that Typst should provide support for spell checking, however that support must be extensible and universal. This is why I think plugins are a good fit; they have the possibility to expose different forms of the input as well as error-reporting capabilities (which in the webapp could be shown inline elegantly)

**Comment by Dherse** [comment]
@emilyyyylime absolutely no need to apologize, I was not offended in any way merely answering your point (which I half agree with you), I hope you did not take it negatively as it wasn't my intent. Sometimes communicating over text can be challenging especially for non-English natives (i.e me).

I agree with you that I'd prefer if we had a kind of "realized" spell checking, so a spell checking API that can see the text as more than the code, perhaps once we have intrinsics discussed in [this Discord channel](https://discord.com/channels/1054443721975922748/1104175637977116722), we could do it at the intrinsics level by having a clear `Paragraph` intrinsics that contains the actual text we can process perhaps.

On the note of plugins I don't think they're a good fit for spell checking because their API is purposefully very limited. Perhaps we could simply expose an LSP-like (i.e web) API that an external tool can query to "intercept" these intrinsic paragraphs or something similar. Anyway, I agree with you that it must not be a "typst spellchecker", a "spellchecker LSP" sounds much more reasonable and maintainable to me.

**Comment by tgross35** [comment]
The best thing for native spellchecking integration is usually to use libenchant since it binds hunspell, aspell, applespell and others and just uses whatever is available. Unfortunately the only Rust crates around are C bindings rather than good abstractions... There also isn't really anything great for grammar, you more or less need to use an online service.

I am the maintainer of zspell and agree that you probably don't want to use it at this time. It is pretty ergonomic so can't hurt to test it out (feel free to give feedback if so!), but it does not yet handle compound words properly and it isn't as performant as I would like (checks are quick but startup is slow, and memory footprint is large for large languages. German uses a few hundred MB and slavic languages are worse).

I do hope to resolve those things in the next few months, so hopefully the situation will be improving soon :)

**Comment by Andrew15-5** [comment]
I want to notify about a Rust implementation of LanguageTool which is WIP AFAICT: https://github.com/bminixhofer/nlprule. I much rather prefer something that doesn't need a VM to run a spellcheck (like the original Java implementation with JVM). Rust is a great "cross-platform substitution" for Java, because it's easier to set up and produces single-binary programs.

**Comment by reknih** [comment]
Pinging @xalbd who is working on spellcheck for the web app. Also see typst/webapp-issues#7, typst/webapp-issues#141

**Comment by antonWetzel** [comment]
After some tries I think checking compiled projects creates better results and less false positives than checking source.

## Example
- https://github.com/antonWetzel/typst-languagetool
- checks spelling, style and grammar, so paragraphs are required

## workflow
1. compile document
1. export text content
    - text/html exporter would make this trivial
    - at the moment changing the styling can help
        - disable hyphenation
        - constant line width (par leading)
        - replace all math with just `0`
1. send text content to checking backend
    - paragraphs can be cached
1. map diagnostics back to source
    - one diagnostic could have many positions in source, but usually just one
    - diagnostic could be filtered for whole document, current file or around the cursor. 

## Problems
- Running another typst compiler needs resources
  - for me
    - LSP
    - Preview
    - Spellcheck
  - compiler hooks could reduce the workload and make projects more reusable
  
## Dream
- the best place to get the text content would be somewhere after the evaluation and before layout.
  - I think evaluation, pagination and layout are intertwined, so this is not easy

**Comment by laurmaedje** [comment]
The web app has had spell check for a while now and for the CLI I consider it out of scope, so I'll close this.

**Comment by TS53** [comment]
A simple spell checker can get implemented using show rules:

```typst
#show "www": seq => panic("spell check: unexpected character sequence", seq)
#show "yyy": seq => panic("spell check: unexpected character sequence", seq)
```

It can also get implemented more general using show regex.

**Comment by Dherse** [comment]
That's a little cursed, I love it!
