### ISSUE TITLE
Tracking issue: More flexible tables

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#3001]
This issue's contents are under construction. More information might be added over time.

- **Check out the planning document:** https://pgbiel.github.io/typst-improv-tables-planning/main.pdf
  - (Source: https://github.com/PgBiel/typst-improv-tables-planning)
- **Discord forge thread link:** https://discord.com/channels/1054443721975922748/1182377294682128445

**Planned Roadmap:** (order and items subject to change)
- [x] 1. **Grid and table API unification** (https://github.com/typst/typst/pull/3009)
    - Related issue(s): https://github.com/typst/typst/issues/2616
- [x] 2. **Per-cell customization** (`table.cell` element, perhaps other initial refactors)
    - [x] Initial cell elements with basic properties (`align`, `fill`, `inset` local overrides) https://github.com/typst/typst/pull/3037
    - [x] Add `x`, `y` fields to cell elements https://github.com/typst/typst/pull/3050
- [x] 3. **Merged cells** (colspan, rowspan)
    - Related issue(s): https://github.com/typst/typst/issues/131
    - [x] Issue https://github.com/typst/typst/issues/1386 will also have to be resolved.
    - [x] Colspans (https://github.com/typst/typst/pull/3239)
    - [x] Rowspans (https://github.com/typst/typst/pull/3501)
- [x] 4. **Line/stroke customization** (https://github.com/typst/typst/pull/3393)
- [ ] 5. **Repeatable headers**
    - Related issue(s): https://github.com/typst/typst/issues/400
    - [x] Headers MVP/in first row (https://github.com/typst/typst/pull/3545)
    - [ ] ~~Headers in arbitrary positions~~ Split off into #5375
    - [ ] ~~Subheaders~~ Split off into https://github.com/typst/typst/issues/5377
- [ ] 6. **Repeatable footers**
    - [x] Footers MVP/in last row (https://github.com/typst/typst/pull/3577)
    - [ ] ~~Footers in arbitrary positions~~ Split off into #5375
    - [ ] ~~Subfooters~~ Split off into https://github.com/typst/typst/issues/5377
- [ ] ~~7. More? (Table orientation, other ideas)~~ Further ideas will become separate issues.

**Comment by PgBiel** [comment]
Closing as the initial round of features was merged into Typst 0.11. Any further features are tracked in separate issues.
