### ISSUE TITLE
Improve functions documentation

### ISSUE THREAD

**Issue by HarmoGlace** [typst/typst#408]
There are several parts of the docs where it is only written "function" as a type itself. But it not enough precise. Each "function" type should be replaced with a typed function, including the arguments and their types (and the expected value).

For instance, on the page [numbering setting,](https://typst.app/docs/reference/layout/page/#parameters--numbering) it is only written that it accepts a "function". I think that it should also add the following indications : `(current_page: integer, total_pages: integer) -> text` or something similar. It would avoid to have to manually guess what the arguments are, and I think that the purpose of the documentation is to make the objects understandable easily and clearly.

**Comment by nunzayin** [comment]
+1 for this. Here's what I've encountered.

So the `str.replace` method's `replacement` argument can accept a `function` that "gets a dictionary for each match and can return individual replacement strings" (according to the current language reference).

The problem is I haven't found any information about what fields (key-value pairs) does the dictionary in question have. Thus, without any LSP support or just experimenting I assume there is no way to get this information. I have found out experimentally its specification:
```typ
(
  start: // a start position of matched string (int)
  end: // end position (int)
  text: // the matched string itself (str)
  captures: // ??? (got no values)
)
```

Please add this to the reference.

**Comment by YDX-2147483647** [comment]
The difficulty lies in the fact that type information is carried by [`CastInfo`](https://docs.rs/typst-library/latest/typst_library/foundations/enum.CastInfo.html), but currently CastInfo can only record that the type is function and nothing more.

> `str.replace`

@nunzayin In your case, please refer to https://typst.app/docs/reference/foundations/str/#definitions-match.
I think we can add a link from `str.replace.replacement` to `str.match`.

**Comment by YDX-2147483647** [comment]
Here's a list of parameters that can take a function.

- [x] array.find.searcher
- [x] array.position.searcher
- [x] array.filter.test
- [x] array.map.mapper
- [x] array.fold.folder
- [x] array.any.test
- [x] array.all.test
- [x] array.sorted.key
- [x] array.sorted.by #5627
- [x] array.dedup.key #6756
- [x] array.reduce.reducer
- [x] plugin.transition.func
- [x] selector.target
- [x] selector.or.others
- [x] selector.and.others
- [x] selector.before.end
- [x] selector.after.start
- [x] str.replace.replacement #6751
- [x] list.marker
- [x] figure.kind
- [x] figure.supplement
- [x] figure.numbering #6757
- [x] footnote.numbering #6757
- [x] heading.numbering #6757
- [x] heading.supplement
- [x] enum.numbering
- [x] numbering.numbering
- [x] outline.target
- [x] outline.indent
- [x] par.line.numbering #6757
- [x] ref.supplement
- [x] table.fill
- [x] table.align
- [x] table.stroke #6764
- [x] table.inset #6764
- [x] math.cancel.angle
- [x] math.equation.numbering #6757
- [x] math.equation.supplement
- [x] grid.fill
- [x] grid.align
- [x] grid.stroke #6764
- [x] grid.inset #6764
- [x] layout.func #7199
- [x] page.numbering #6757
- [x] counter.key
- [x] counter.display.numbering
- [x] ~~counter.at.selector~~ No need because the function selector will not receive arguments.
- [x] counter.update.update
- [x] ~~locate.selector~~ No need because the function selector will not receive arguments.
- [x] query.target
- [x] ~~state.at.selector~~ No need because the function selector will not receive arguments.
- [x] state.update.update

<details>
<summary>Source</summary>

First, generate `docs.json` using `docs/src/main.rs`. (Or download from https://ydx-typst.netlify.app/docs.json, which is [built on netlify](https://forum.typst.app/t/guide-preview-typst-app-docs-of-your-pr-on-netlify/5291).)

Then, run the following command.

```bash
jq '.. | . as $p | .params? // empty | .[] | { name: [$p.path[], $p.name, .name] | join("."), types: .types }' docs.json --compact-output | rg '"function"' > params.jsonl
```

</details>


https://github.com/typst/typst/pull/7199#issuecomment-3451552032:
> Thanks! It's very nice that all functions are dealt with now. That said, I'm not sure whether that covers the intent of this issue or whether the issue author wanted a more structured view of the function signatures. For now, I'd prefer to keep the issue open.
