### ISSUE TITLE
Tracking issue: HTML export

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#5512]
This issue documents the progress of development on HTML export. It's not for discussion of specific features, which should occur in other issues or on Discord.

- [Feature request issue:](https://github.com/typst/typst/issues/721) #721
- [Discord forge thread:](https://discord.com/channels/1054443721975922748/1269208488978939946) Primary place for design discussions

### Plan

HTML export will be developed iteratively, merging individual chunks of work instead of building up huge branches. For this reason, it will stay behind a **feature flag** (`typst c file.typ --format html --feature html`) and warn upon use. It will be available for experimentation, but it's not intended for production use.

There is not yet a timeline for when we'll move things out of the feature flag, but likely once we are happy with the general usability of the feature and think it's ready for more widespread use.

The work on Typst's HTML export is generously [**supported by the NLnet foundation**](https://nlnet.nl/project/Typst-HTML/) with a grant financing 6 months of full-time work by external contributor @01mf02. Many thanks to both!

### Scope

Our primary focus in this initial phase of work will be on **generating semantic HTML with no CSS.** This already supports various use cases where CSS can be added separately and, in my view, unlocks the main benefit of supporting HTML export in the first place: To share the same content between print and web.

Rich **customization of the semantic output structure is explicitly in scope.** We'll provide sensible defaults via built-in show rules, but you will be able to write your own target-aware code to generate whatever HTML is best for your use case. The goal is to encapsulate this target awareness into show rules & templates as much as possible, such that the main content is left untouched by it.

We also want to cover various different use cases ranging from **single-file output** or even just **fragments** of HTML for inclusion in web pages to **multi-file output** with fine control over paths & assets (e.g. for a blog).

### Milestones

(Will be expanded as work progresses, (~) means partially implemented)

- [x] Foundations
  - [x] Feature flag & output format
  - [x] Generic `html.elem` API for outputing arbitrary HTML elements
  - [x] Basic introspection in HTML (queries, counter, state)
- [ ] CLI
  - [ ] `typst watch` server
- [ ] Output quality
  - [x] Respect escaping rules and allowed charsets
  - [ ] Ensure spec-compliant HTML element nesting
  - [ ] Accessibility audit (towards the end)
- [ ] Customization
  - [ ] Output mode:
    - [x] Single-file standalone output
    - [ ] Multi-file output with path & asset control
    - [ ] Fragment output for inclusion in larger pages
  - [ ] Minified/Pretty-printed output
  - [ ] Safe/unsafe output (safe output should prevent XSS)
  - [ ] `<html>`, `<head>`, `<body>` customization
  - [ ] HTML5/XHTML[^1] output
- [ ] HTML APIs
  - [ ] (~) `target` API for output-aware show rules
  - [ ] (~) `html.frame` API for laying out parts of the output and embedding as SVG (e.g. for figures)
  - [ ] `html.*` typed element constructors
- [ ] Support for built-in elements
  - [ ] Model (Most important one for semantics)
    - [x] Paragraph, Paragraph break (`par`, `parbreak`)
    - [x] Strong (`strong`)
    - [x] Emph (`emph`)
    - [ ] (~) Document (`document`)
    - [ ] New `title` element which maps to `<h1>`
    - [ ] (~) Heading (`heading`), which map to `<h2>`, ...
    - [ ] (~) List (`list`)
    - [ ] (~) Enum (`enum`)
    - [ ] (~) Terms (`terms`)
    - [ ] (~) Link (`link`)
      - [x] URL links
      - [ ] Support for labels as HTML IDs
      - [ ] Auto-generated IDs for location linking
        - [ ] Linking within HTML files
        - [ ] Linking across HTML files
    - [ ] (~) Figure (`figure`)
    - [ ] Table (`table`)
    - [ ] Reference (`ref`)
    - [ ] Footnote (`footnote`)
    - [ ] Quote (`quote`)
    - [ ] Outline (`outline`)
    - [ ] Bibliography, cite (`bibliography`, `cite`)
  - [ ] Math (Rendering to MathML)
  - [ ] Text (likely just a subset)
  - [ ] Visualization (possibly just a subset)
  - [ ] Layout (we'll have to see how much of it makes sense)

## Future plans

Things that we'll likely work on in the future, but which are not contained in the initial phase of work:

- EPUB support
- CSS support

[^1]: To speak in the more correct terms of the WHATWG spec: HTML vs. XML serialization
